name: kkiapay_flutter_sdk
description: KKiaPay allows businesses to safely receive payments by mobile money, credit card and bank account.
version: 1.3.0-dev.14
homepage: "https://kkiapay.me/"

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


  stacked_shared: ^1.4.0
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  url_launcher: ^6.2.1           # used for wave payment
  http: ^1.2.1
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  stacked_generator:


flutter:
  uses-material-design: true

  plugin:
    platforms:
      android:
        package: co.kkiapay.kkiapay_flutter_sdk
        pluginClass: KkiapayFlutterSdkPlugin
      ios:
        pluginClass: KkiapayFlutterSdkPlugin
      web:
        pluginClass: KkiapayFlutterSdkWeb
        fileName: kkiapay_flutter_sdk_web.dart